version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - rabbitmq
    networks:
      - my_network

  auth-service:
    build: 
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - mongoUrl=mongodb://mongo:27017/auth-service
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - my_network

  product-service:
    build: 
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - mongoUrl=mongodb://mongo:27017/product-service
      - amqplibServeUrl=amqp://rabbitmq:5672
    depends_on:
      - order-service
      - rabbitmq
      - mongo
    networks:
      - my_network

  order-service:
    build: 
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      - mongoUrl=mongodb://mongo:27017/order-service
      - amqplibServeUrl=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data: